CREATE TABLE Items (
  ItemID STRING(64) NOT NULL,
  ItemName STRING(1024) NOT NULL,
  Price INT64 NOT NULL,
  CreatedAt TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp=true),
  UpdatedAt TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp=true)
) PRIMARY KEY (ItemID);

CREATE TABLE Orders (
  UserID STRING(64) NOT NULL,
  OrderID STRING(64) NOT NULL,
  Amount INT64 NOT NULL,
  CommitedAt TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp=true)
) PRIMARY KEY (UserID, OrderID DESC), INTERLEAVE IN PARENT Users ON DELETE CASCADE;

CREATE TABLE OrderDetails (
  UserID STRING(64) NOT NULL,
  OrderID STRING(64) NOT NULL,
  OrderDetailID INT64 NOT NULL,
  ItemID STRING(64) NOT NULL,
  Price INT64 NOT NULL,
  Quantity INT64 NOT NULL,
  CommitedAt TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp=true)
) PRIMARY KEY (UserID, OrderID DESC, OrderDetailID), INTERLEAVE IN PARENT Orders ON DELETE CASCADE;
