steps:
- name: 'golang:1.21-bullseye'
  entrypoint: 'go'
  args: ['build', '-o', 'app', 'github.com/sinmetal/srunner/cmd/server/tweet']
  env: ['CGO_ENABLED=0']
images:
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/sinmetal/srunner:$COMMIT_SHA'
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/sinmetal/srunner:$BRANCH_NAME'