steps:
- name: gcr.io/cloud-builders/docker
  args: ['run', '-d', '--network=cloudbuild', '-p', '9999:9999', '--name=handy-spanner', 'gcr.io/gcpug-container/handy-spanner:v0.1.0']
- name: jwilder/dockerize:0.6.1
  args: ['dockerize', '-timeout=60s', '-wait=tcp://handy-spanner:9999']
- name: 'golang:1.14-stretch'
  entrypoint: 'go'
  args: ['test', '-v', './...']
  env:
    - 'GO111MODULE=on'
    - 'SPANNER_EMULATOR_HOST=handy-spanner:9999'
- name: 'golang:1.14-stretch'
  entrypoint: 'go'
  args: ['build', '.']
  env: ['GO111MODULE=on']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/sinmetal/srunner/$BRANCH_NAME:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - set
    - image
    - deployment/srunner-dep
    - srunner-dep=gcr.io/$PROJECT_ID/sinmetal/srunner/$BRANCH_NAME:$COMMIT_SHA
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=asia-northeast1-b'
    - 'CLOUDSDK_CONTAINER_CLUSTER=sinmetal-tokyo'
images: ['gcr.io/$PROJECT_ID/sinmetal/srunner/$BRANCH_NAME:$COMMIT_SHA']