steps:
- name: 'golang:1.14-stretch'
  entrypoint: 'go'
  args: ['test', '-v', './...']
  env:
    - 'GO111MODULE=on'
- name: 'golang:1.14-stretch'
  entrypoint: 'go'
  args: ['build', '.']
  env: ['GO111MODULE=on']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/sinmetal/srunner/$BRANCH_NAME:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - set
    - image
    - deployment/srunner-dep
    - srunner-dep=gcr.io/$PROJECT_ID/sinmetal/srunner/$BRANCH_NAME:$COMMIT_SHA
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=asia-northeast1-b'
    - 'CLOUDSDK_CONTAINER_CLUSTER=sinmetal-tokyo'
images: ['gcr.io/$PROJECT_ID/sinmetal/srunner/$BRANCH_NAME:$COMMIT_SHA']