apiVersion: apps/v1
kind: Deployment
metadata:
  name: srunner-dep
  namespace: metalapps
  labels:
    app: srunner-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srunner-dep
  template:
    metadata:
      labels:
        app: srunner-dep
    spec:
      serviceAccountName: metalapps-default
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      containers:
        - name: srunner-dep
          image: asia-northeast1-docker.pkg.dev/$PROJECT_ID/srunner/$BRANCH_NAME:$COMMIT_SHA
          envFrom:
            - configMapRef:
                name: srunner-config
