apiVersion: apps/v1
kind: Deployment
metadata:
  name: srunner-tokyo-dep
  labels:
    app: srunner-tokyo-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srunner-tokyo-dep
  template:
    metadata:
      labels:
        app: srunner-tokyo-dep
    spec:
      containers:
        - name: srunner-tokyo-dep
          image: gcr.io/mercari-p-sinmetal/sinmetal/srunner/runner-v2:efb597470a2a66105dcc786b955eefbf24ddd5e2
          envFrom:
            - configMapRef:
                name: srunner-tokyo-config
          resources:
            limits:
              cpu: "2"
            requests:
              cpu: "1"
