CREATE TABLE ItemOrderNoFK (
	ItemOrderID STRING(MAX) NOT NULL,
	ItemID STRING(MAX) NOT NULL,
	UserID STRING(MAX) NOT NULL,
	CommitedAt TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp=true),
) PRIMARY KEY (ItemOrderID)